server.port: ${SERVER_PORT:8081}

meterhub.server.socket:
  host: ${METERHUB_SERVER_HOST:127.0.0.1}
  port: ${METERHUB_SERVER_PORT:9999}

meterhub.server.sftp:
  host: ${METERHUB_SERVER_SFTP_HOST:10.1.1.4}
  port: ${METERHUB_SERVER_SFTP_PORT:10012}
  user: ${METERHUB_SERVER_SFTP_USER:vking}
  password: ${METERHUB_SERVER_SFTP_PASSWORD:Vking1357!}

logging.level:
  root: INFO
  com.vking: DEBUG

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.vking.duhv.meterhub.client.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
